name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Set AWS and Slack environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID=testing" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=testing" >> $GITHUB_ENV
          echo "AWS_SECURITY_TOKEN=testing" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=testing" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=testing" >> $GITHUB_ENV
          echo "SLACK_BOT_TOKEN=dummy_token_value" >> $GITHUB_ENV

      - name: Run unit tests
        run: pytest src/tests/unit

      - name: Run integration tests
        run: pytest src/tests/integration

      - name: Run tests with coverage
        run: |
          pip install pytest-cov
          pytest --cov=src --cov-report=xml src/tests/unit src/tests/integration

